export const indexHtml = `
<!DOCTYPE html>

<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
</head>

<body>
	<main class="container">
		<hgroup>
			<h1>Google Maps Images Getter</h1>
			<p>Get full images of Google Maps images with a single URL.</p>
		</hgroup>
		<form>
			<fieldset>
				<label for="url">URL</label>
				<input type="text" name="url" placeholder="URL" />
			</fieldset>

			<input type="submit" value="▶ Go" />
		</form>
		<p>Copy the URL of the image from Google Maps to the box above and hit the button to get the full image.</p>
		<p>Sample URLs as examples:</p>
		<ul>
			<li>Share link: <a href="https://maps.app.goo.gl/ZBfcVSpzsDq4J55t8" target="_blank" rel="noopener noreferrer">https://maps.app.goo.gl/ZBfcVSpzsDq4J55t8</a></li>
			<li>When opening an image: <a href="https://www.google.com/maps/place/Monas/@-6.1753924,106.8271528,3a,75y,90t/data=!3m7!1e2!3m5!1sAF1QipM7bvPYAGTLMVv6UNLUdR7eaURoBM8cg2fVMvMS!2e10!3e12!7i4000!8i3000!4m9!3m8!1s0x2e69f5d2e764b12d:0x3d2ad6e1e0e9bcc8!8m2!3d-6.1753924!4d106.8271528!10e5!14m1!1BCgIgARICEAM!16zL20vMDNxN2hz" target="_blank" rel="noopener noreferrer">https://www.google.com/maps/place/Monas/@-6.1753924,106.8271528,3a,75y,90t/data=!3m7!1e2!3m5!1sAF1QipM7bvPYAGTLMVv6UNLUdR7eaURoBM8cg2fVMvMS!2e10!3e12!7i4000!8i3000!4m9!3m8!1s0x2e69f5d2e764b12d:0x3d2ad6e1e0e9bcc8!8m2!3d-6.1753924!4d106.8271528!10e5!14m1!1BCgIgARICEAM!16zL20vMDNxN2hz</a></li>
			<li>Direct URL (if available): <a href="https://lh5.googleusercontent.com/p/AF1QipM7bvPYAGTLMVv6UNLUdR7eaURoBM8cg2fVMvMS=w203-h152-k-no" target="_blank" rel="noopener noreferrer">https://lh5.googleusercontent.com/p/AF1QipM7bvPYAGTLMVv6UNLUdR7eaURoBM8cg2fVMvMS=w203-h152-k-no</a></li>
		</ul>
	</main>
	<footer class="container">
		<p>Made by <a href="https://s.id/HansTM" target="_blank">Hans TM</a>. Built using <a href="https://workers.cloudflare.com/" target="_blank">Cloudflare Workers</a>. <a herf="https://www.typescriptlang.org/" target="_blank">TypeScript</a>, and <a href="https://picocss.com/" target="_blank">Pico CSS</a>.</p>
		<p>Repository: <a href="https://github.com/HansTM/gmaps-imgs" target="_blank">https://github.com/HansTM/gmaps-imgs</a></p>
	</footer>
</body>
`

export var googleDomains = [
	".google.com",
	".google.ad",
	".google.ae",
	".google.com.af",
	".google.com.ag",
	".google.al",
	".google.am",
	".google.co.ao",
	".google.com.ar",
	".google.as",
	".google.at",
	".google.com.au",
	".google.az",
	".google.ba",
	".google.com.bd",
	".google.be",
	".google.bf",
	".google.bg",
	".google.com.bh",
	".google.bi",
	".google.bj",
	".google.com.bn",
	".google.com.bo",
	".google.com.br",
	".google.bs",
	".google.bt",
	".google.co.bw",
	".google.by",
	".google.com.bz",
	".google.ca",
	".google.cd",
	".google.cf",
	".google.cg",
	".google.ch",
	".google.ci",
	".google.co.ck",
	".google.cl",
	".google.cm",
	".google.cn",
	".google.com.co",
	".google.co.cr",
	".google.com.cu",
	".google.cv",
	".google.com.cy",
	".google.cz",
	".google.de",
	".google.dj",
	".google.dk",
	".google.dm",
	".google.com.do",
	".google.dz",
	".google.com.ec",
	".google.ee",
	".google.com.eg",
	".google.es",
	".google.com.et",
	".google.fi",
	".google.com.fj",
	".google.fm",
	".google.fr",
	".google.ga",
	".google.ge",
	".google.gg",
	".google.com.gh",
	".google.com.gi",
	".google.gl",
	".google.gm",
	".google.gr",
	".google.com.gt",
	".google.gy",
	".google.com.hk",
	".google.hn",
	".google.hr",
	".google.ht",
	".google.hu",
	".google.co.id",
	".google.ie",
	".google.co.il",
	".google.im",
	".google.co.in",
	".google.iq",
	".google.is",
	".google.it",
	".google.je",
	".google.com.jm",
	".google.jo",
	".google.co.jp",
	".google.co.ke",
	".google.com.kh",
	".google.ki",
	".google.kg",
	".google.co.kr",
	".google.com.kw",
	".google.kz",
	".google.la",
	".google.com.lb",
	".google.li",
	".google.lk",
	".google.co.ls",
	".google.lt",
	".google.lu",
	".google.lv",
	".google.com.ly",
	".google.co.ma",
	".google.md",
	".google.me",
	".google.mg",
	".google.mk",
	".google.ml",
	".google.com.mm",
	".google.mn",
	".google.com.mt",
	".google.mu",
	".google.mv",
	".google.mw",
	".google.com.mx",
	".google.com.my",
	".google.co.mz",
	".google.com.na",
	".google.com.ng",
	".google.com.ni",
	".google.ne",
	".google.nl",
	".google.no",
	".google.com.np",
	".google.nr",
	".google.nu",
	".google.co.nz",
	".google.com.om",
	".google.com.pa",
	".google.com.pe",
	".google.com.pg",
	".google.com.ph",
	".google.com.pk",
	".google.pl",
	".google.pn",
	".google.com.pr",
	".google.ps",
	".google.pt",
	".google.com.py",
	".google.com.qa",
	".google.ro",
	".google.ru",
	".google.rw",
	".google.com.sa",
	".google.com.sb",
	".google.sc",
	".google.se",
	".google.com.sg",
	".google.sh",
	".google.si",
	".google.sk",
	".google.com.sl",
	".google.sn",
	".google.so",
	".google.sm",
	".google.sr",
	".google.st",
	".google.com.sv",
	".google.td",
	".google.tg",
	".google.co.th",
	".google.com.tj",
	".google.tl",
	".google.tm",
	".google.tn",
	".google.to",
	".google.com.tr",
	".google.tt",
	".google.com.tw",
	".google.co.tz",
	".google.com.ua",
	".google.co.ug",
	".google.co.uk",
	".google.com.uy",
	".google.co.uz",
	".google.com.vc",
	".google.co.ve",
	".google.co.vi",
	".google.com.vn",
	".google.vu",
	".google.ws",
	".google.rs",
	".google.co.za",
	".google.co.zm",
	".google.co.zw",
	".google.cat"
]

